import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");

const files = {
  api: "src/lib/api.ts",
  list: "src/app/knowledge/page.tsx",
  detail: "src/app/knowledge/[id]/page.tsx",
  workbench: "src/components/wiki/WikiWorkbench.tsx",
  page: "src/components/wiki/WikiPagePanel.tsx",
  graph: "src/components/wiki/WikiGraphPanel.tsx",
  graphPage: "src/app/knowledge/[id]/wiki/graph/page.tsx",
  lint: "src/components/wiki/WikiLintPanel.tsx",
  crystallize: "src/components/wiki/WikiCrystallizePanel.tsx",
  chatWikiModal: "src/components/chat/WikiModal.tsx",
  sidebar: "src/components/Sidebar.tsx",
};

const read = (key) => fs.readFileSync(path.join(root, files[key]), "utf8");
const checks = [
  ["api", "repairWikiKbIssues"],
  ["api", "cancelTask"],
  ["api", "acceptGeneratedWikiKbPage"],
  ["api", "discardGeneratedWikiKbPage"],
  ["api", "deleteWikiKbPage"],
  ["api", "capability: ProviderCapability"],
  ["workbench", "graphOptions"],
  ["workbench", "pageFilters"],
  ["workbench", "handleGraphNodeSelect"],
  ["workbench", "handleIssueAction"],
  ["workbench", "sidebar"],
  ["workbench", "WikiPageDirectory"],
  ["workbench", "resources"],
  ["workbench", "WikiResourcePane"],
  ["workbench", "wikiWorkbenchTab"],
  ["workbench", "loadWikiPages"],
  ["workbench", "pageLoading"],
  ["workbench", "loadSelectedPageDetail"],
  ["workbench", "loadWikiGraph"],
  ["workbench", "loadWikiLint"],
  ["workbench", "ensureTabData"],
  ["workbench", "renderResources"],
  ["workbench", "WikiResourceContext"],
  ["workbench", "replaceWikiPageUrl"],
  ["workbench", 'searchParams.set("wikiPage"'],
  ["workbench", "window.history.replaceState"],
  ["list", "ModelSettingsDialog"],
  ["list", "onSettings"],
  ["list", "selectedSettingsLLM"],
  ["list", "settingsProbeResult"],
  ["list", 'capability: "chat"'],
  ["list", "NexAgent wiki model test"],
  ["list", "reindexBadgeLabel"],
  ["list", "需重编译"],
  ["detail", "WikiSourceToolbar"],
  ["detail", "compileWikiKb"],
  ["detail", "handleWikiCompile"],
  ["detail", "handleWikiRetryFailedCompile"],
  ["detail", "WikiQuickUpload"],
  ["detail", "WikiFileList"],
  ["detail", "WikiCompactHeader"],
  ["detail", "WikiSourceSection"],
  ["detail", "wikiCompactKnowledgeCard"],
  ["detail", "wikiSourcePanelHeader"],
  ["detail", "wikiFileRow"],
  ["detail", "wikiSourceFileNameLine"],
  ["detail", "wikiSourceFileMetaLine"],
  ["detail", "wikiSourceItemMain"],
  ["detail", "sourceStatusPill"],
  ["detail", "sourceTypeLabel"],
  ["detail", "WikiTaskQueue"],
  ["detail", "WikiStatusStrip"],
  ["detail", "wikiLlmStatusLabel"],
  ["detail", "compactModelName"],
  ["detail", "wikiLlmStatusBadge"],
  ["detail", 'provider.startsWith("config-")'],
  ["detail", "wikiStatusStrip"],
  ["detail", "llmLabel"],
  ["detail", "candidateCount"],
  ["detail", "needsReviewCount"],
  ["detail", "failedSourceCount"],
  ["detail", "applyWikiStatusFilter"],
  ["detail", "候选"],
  ["detail", "待复核"],
  ["detail", "失败来源"],
  ["detail", "重新编译 Wiki"],
  ["detail", "强制重编译 Wiki"],
  ["detail", "retry_failed: true"],
  ["detail", "showUpload"],
  ["detail", "uploadDialogDropzone"],
  ["detail", "wikiUploadDialogTrigger"],
  ["detail", "taskQueueTrigger"],
  ["detail", "taskQueuePopover"],
  ["detail", "wikiSidebar"],
  ["detail", "activeSourceFileId"],
  ["detail", "onToggleSourceFilter"],
  ["page", "wiki-link"],
  ["page", "urlTransform={preserveWikiUrl}"],
  ["page", "function preserveWikiUrl"],
  ["page", "resolveWikiHref"],
  ["page", "pathLookup"],
  ["page", "normalizeWikiPath"],
  ["page", "href?.startsWith(\"wiki/\")"],
  ["page", "export function WikiPageDirectory"],
  ["page", "compactFilterBar"],
  ["page", "pageDirectoryCompactHeader"],
  ["page", "compactSelectFilter"],
  ["page", "wikiDocumentBody"],
  ["page", "text-blue-700"],
  ["page", "acceptGeneratedWikiKbPage"],
  ["page", "discardGeneratedWikiKbPage"],
  ["page", "sourceFilter"],
  ["graph", "includeWeak"],
  ["graph", "maxEdges"],
  ["graph", "nodesDraggable"],
  ["graph", "showInteractive"],
  ["graph", "核心节点"],
  ["graph", "关系详情"],
  ["graph", "WikiGraphExplorerShell"],
  ["graph", "typeFilters"],
  ["graph", "communityFilters"],
  ["graph", "selectedNodeId"],
  ["graph", "selectedEdgeKey"],
  ["graph", "focusNodeId"],
  ["graph", "onEdgeClick"],
  ["graph", "GraphSignalList"],
  ["graph", "关系信号"],
  ["graph", "相邻页面"],
  ["graph", "类型相同"],
  ["graph", "onFitView"],
  ["graph", "draftOptions"],
  ["graph", "setDraftOptions"],
  ["graph", "applyGraphOptions"],
  ["graph", "onReload(nextOptions)"],
  ["graph", "layoutMode"],
  ["graph", "graphLayoutModes"],
  ["graph", "社区布局"],
  ["graph", "环形布局"],
  ["graph", "强度布局"],
  ["graph", "页面类型"],
  ["graph", "社区"],
  ["graph", "关系列表"],
  ["workbench", "refreshGraph"],
  ["workbench", "filterWikiPages"],
  ["workbench", "wikiResourcePaneCompact"],
  ["workbench", "xl:grid-cols-[minmax(320px,0.72fr)_minmax(680px,1.28fr)]"],
  ["graphPage", "graphOptionsRef"],
  ["graphPage", "图谱说明"],
  ["graphPage", "页面关系 / 主题结构 / 来源关联"],
  ["lint", "一键 AI 生成修复候选"],
  ["lint", "WikiRepairResultCard"],
  ["lint", "repairResult"],
  ["lint", "lastRepairItems"],
  ["lint", "cancelTask"],
  ["lint", "cancelRepairTask"],
  ["lint", "取消修复"],
  ["lint", "cancel_requested"],
  ["lint", "force"],
  ["lint", "skipped_issues"],
  ["lint", "处理候选"],
  ["lint", "AI 修复已加入任务队列"],
  ["lint", "fetchIngestionJobs"],
  ["lint", "repairTask"],
  ["lint", "pollRepairTask"],
  ["lint", "AI 修复任务完成"],
  ["lint", "任务完成后已自动刷新"],
  ["lint", "groupedIssues"],
  ["lint", "repairWikiKbIssues"],
  ["crystallize", "crystalTemplates"],
  ["crystallize", "applyCrystalTemplate"],
  ["crystallize", "clearCrystalDraft"],
  ["crystallize", "confidenceSegments"],
  ["crystallize", "sourceIds"],
  ["crystallize", "sourcesText"],
  ["crystallize", "selectedSourceCount"],
  ["crystallize", "会议纪要"],
  ["crystallize", "结论沉淀"],
  ["crystallize", "问题排查"],
  ["crystallize", "查询结果"],
  ["crystallize", "临时笔记"],
  ["crystallize", "预览确认并生成页面"],
  ["chatWikiModal", "WikiCrystallizePageType"],
  ["chatWikiModal", "pageType"],
  ["chatWikiModal", "page_type"],
  ["chatWikiModal", "pageHref"],
  ["chatWikiModal", "打开 Wiki 页面"],
  ["chatWikiModal", "作为笔记"],
  ["chatWikiModal", "作为问答"],
  ["detail", "taskKindLabel"],
  ["detail", "wiki_repair"],
  ["detail", "Wiki 编译"],
  ["detail", "visibleJobs"],
  ["detail", "actionableHistoryJobs"],
  ["detail", "hiddenJobCount"],
  ["detail", "showAllJobs"],
  ["detail", "taskTimeValue"],
  ["detail", "rawTime < 10000000000"],
  ["detail", "taskFileIds"],
  ["detail", "successfulTaskFileTimes"],
  ["detail", "isObsoleteHistoryTask"],
  ["detail", "活跃"],
  ["detail", "历史任务"],
  ["sidebar", 'import Link from "next/link"'],
  ["sidebar", "<Link"],
  ["sidebar", "prefetch={false}"],
];

const absentChecks = [
  ["page", "page.excerpt"],
  ["detail", "xl:grid-cols-[340px_minmax(0,1fr)]"],
  ["page", "xl:grid-cols-[360px_minmax(0,1fr)]"],
  ["detail", "<WikiModelPanel"],
  ["detail", "Wiki LLM 配置"],
  ["detail", "line-clamp-2 text-sm leading-6"],
  ["detail", "任务{jobs.length"],
  ["workbench", "const [nextPages, nextGraph, nextLint] = await Promise.all"],
  ["workbench", "await loadSelectedPage(nextPageId)"],
  ["page", "wiki-new:"],
  ["page", "createLinkedPage"],
  ["page", "crystallizeWikiKbPage"],
  ["page", "创建中..."],
  ["page", "markdown-body rounded-xl border"],
  ["page", "max-h-[720px]"],
  ["graph", "onChange={(event) => onOptionsChange({ q: event.target.value })}"],
  ["graphPage", "}, [graphOptions, id])"],
  ["workbench", "fetchWikiKbPages(kb.kb_id, compactParams(pageFilters))"],
  ["workbench", "function compactParams"],
  ["api", "fetchWikiPages"],
  ["api", "fetchWikiPage("],
  ["api", "deleteWikiPage("],
  ["api", "${BASE}/wiki/pages"],
  ["sidebar", "no-html-link-for-pages"],
  ["sidebar", "<a\n"],
  ["sidebar", "</a>"],
  ["list", "LLM Wiki"],
  ["list", 'requiresReindex ? <Badge variant="warning">需重建</Badge> : null'],
  ["detail", "LLM Wiki"],
  ["detail", "return `LLM ${provider}/${model}`;"],
  ["detail", "onRetryFailed={handleProcessAll}"],
  ["detail", "Number(right.updated_at || right.created_at || 0)"],
  ["detail", "const priorityHistoryJobs = historyJobs.filter((job) => job.status !== \"completed\").slice(0, 3);"],
  ["graphPage", "LLM Wiki"],
];

const failures = [];
for (const [key, needle] of checks) {
  if (!read(key).includes(needle)) {
    failures.push(`${files[key]} is missing ${needle}`);
  }
}
for (const [key, needle] of absentChecks) {
  if (read(key).includes(needle)) {
    failures.push(`${files[key]} still contains ${needle}`);
  }
}

if (failures.length) {
  console.error(failures.join("\n"));
  process.exit(1);
}

console.log("wiki ui checks passed");
