# NexAgent setup wizard.
# PowerShell 5.1 compatible. Creates .env and config.yaml from user choices.

param(
    [ValidateSet("siliconflow", "openai", "deepseek", "openrouter", "ollama")]
    [string]$Provider = "",
    [string]$ApiKey = "",
    [string]$Model = "",
    [string]$BaseUrl = "",
    [switch]$EnableKnowledge,
    [switch]$Force,
    [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)

function Ask-Choice {
    param([string]$Prompt, [string]$Default)
    if ($NonInteractive) { return $Default }
    $value = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}

function Ask-Secret {
    param([string]$Prompt)
    if ($NonInteractive -or $ApiKey) { return $ApiKey }
    $secure = Read-Host $Prompt -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

function Provider-Defaults {
    param([string]$Name)
    switch ($Name) {
        "openai" {
            return @{
                Env = "OPENAI_API_KEY"; Display = "OpenAI"; Provider = "openai";
                Model = "gpt-4o-mini"; BaseUrl = "https://api.openai.com/v1"
            }
        }
        "deepseek" {
            return @{
                Env = "DEEPSEEK_API_KEY"; Display = "DeepSeek"; Provider = "openai";
                Model = "deepseek-chat"; BaseUrl = "https://api.deepseek.com/v1"
            }
        }
        "openrouter" {
            return @{
                Env = "OPENROUTER_API_KEY"; Display = "OpenRouter"; Provider = "openai";
                Model = "openai/gpt-4o-mini"; BaseUrl = "https://openrouter.ai/api/v1"
            }
        }
        "ollama" {
            return @{
                Env = ""; Display = "Ollama"; Provider = "ollama";
                Model = "llama3.1"; BaseUrl = "http://localhost:11434"
            }
        }
        default {
            return @{
                Env = "SILICONFLOW_API_KEY"; Display = "SiliconFlow"; Provider = "openai";
                Model = "Qwen/Qwen2.5-7B-Instruct"; BaseUrl = "https://api.siliconflow.cn/v1"
            }
        }
    }
}

function Write-FileSafely {
    param([string]$Path, [string]$Content)
    if ((Test-Path $Path) -and (-not $Force)) {
        Write-Host "[skip] $Path already exists. Use -Force to replace it." -ForegroundColor Yellow
        return
    }
    if (Test-Path $Path) {
        $backup = "$Path.bak-$(Get-Date -Format 'yyyyMMddHHmmss')"
        Copy-Item $Path $backup
        Write-Host "[backup] $backup" -ForegroundColor DarkGray
    }
    Set-Content -Path $Path -Value $Content -Encoding UTF8
    Write-Host "[ok] wrote $Path" -ForegroundColor Green
}

Push-Location $Root

if (-not $Provider) {
    Write-Host ""
    Write-Host "NexAgent Setup" -ForegroundColor Cyan
    Write-Host "Providers: siliconflow, openai, deepseek, openrouter, ollama" -ForegroundColor DarkGray
    $Provider = Ask-Choice "Choose model provider" "siliconflow"
}

$defaults = Provider-Defaults $Provider
if (-not $Model) { $Model = Ask-Choice "Model id" $defaults.Model }
if (-not $BaseUrl) { $BaseUrl = Ask-Choice "Base URL" $defaults.BaseUrl }
if (-not $ApiKey -and $defaults.Env) { $ApiKey = Ask-Secret "API key for $($defaults.Display) (input hidden, optional)" }

$envLines = @(
    "# NexAgent environment",
    "NEXAGENT_VERSION=0.1.0",
    "NEXAGENT_DEBUG=0",
    "NEXAGENT_CORS_ORIGINS=*",
    "NEXAGENT_DATA_DIR=.nexagent",
    "",
    "SILICONFLOW_API_KEY=",
    "OPENAI_API_KEY=",
    "DEEPSEEK_API_KEY=",
    "OPENROUTER_API_KEY=",
    "ANTHROPIC_API_KEY=",
    "GOOGLE_API_KEY=",
    "TAVILY_API_KEY=",
    "",
    "POSTGRES_USER=nexagent",
    "POSTGRES_PASSWORD=nexagent",
    "POSTGRES_DB=nexagent",
    "DATABASE_URL=postgresql://nexagent:nexagent@localhost:5432/nexagent",
    "REDIS_URL=redis://localhost:6379/0",
    "",
    "MILVUS_HOST=localhost",
    "MILVUS_PORT=19530",
    "NEO4J_URI=bolt://localhost:7687",
    "NEO4J_USER=neo4j",
    "NEO4J_PASSWORD=nexagent"
)
if ($defaults.Env -and $ApiKey) {
    for ($i = 0; $i -lt $envLines.Count; $i++) {
        if ($envLines[$i] -eq "$($defaults.Env)=") {
            $envLines[$i] = "$($defaults.Env)=$ApiKey"
        }
    }
}

$apiKeyYaml = if ($defaults.Env) { "`$$($defaults.Env)" } else { "" }
$vectorEnabled = if ($EnableKnowledge) { "true" } else { "false" }
$graphEnabled = if ($EnableKnowledge) { "true" } else { "false" }

$configYaml = @"
# Generated by scripts/setup.ps1
config_version: 2
debug: false
default_model: default

models:
  - name: default
    display_name: $($defaults.Display) Default
    provider: $($defaults.Provider)
    model: $Model
    api_key: $apiKeyYaml
    base_url: $BaseUrl
    supports_streaming: true

knowledge:
  milvus_host: localhost
  milvus_port: 19530
  neo4j_uri: bolt://localhost:7687
  neo4j_user: neo4j
  neo4j_password: `$NEO4J_PASSWORD
  embedding:
    model: BAAI/bge-large-zh-v1.5
    base_url: https://api.siliconflow.cn/v1
    api_key: `$SILICONFLOW_API_KEY
    dimension: 1024
  vector_store:
    enabled: $vectorEnabled
    provider: milvus
  graph_store:
    enabled: $graphEnabled
    provider: neo4j

web_search:
  provider: auto
  preferred_provider: duckduckgo
  enabled_providers:
    - duckduckgo
  max_results: 5
  fetch_max_chars: 12000

mcp_servers: []

sandbox:
  enabled: true
  provider: local
  base_dir: .nexagent
  timeout_seconds: 30
  max_output_chars: 8000
  allow_bash: true
  audit_enabled: true
"@

Write-FileSafely (Join-Path $Root ".env") ($envLines -join [Environment]::NewLine)
Write-FileSafely (Join-Path $Root "config.yaml") $configYaml

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  .\scripts\doctor.ps1" -ForegroundColor White
Write-Host "  .\start.ps1" -ForegroundColor White
if ($EnableKnowledge) {
    Write-Host "  .\start.ps1 -kb   # when you need Milvus/Neo4j" -ForegroundColor White
}

Pop-Location
